version: '3'
services:
  backend-db:
    build: mariadb
    environment:
      MYSQL_DATABASE: "osyc"
      MYSQL_USERNAME: "osyc"
      MYSQL_PASSWORD: "osyc"
  backend:
    build: backend
    depends_on:
      - backend-db
    ports:
      - "127.0.0.1:7802:80"
  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - "127.0.0.1:7801:80"
